### ISSUE TITLE
App not finding environment variables

### ISSUE THREAD

**Issue by pierwill** [bonitoo-io/iot-center-v2#22]
__Expected Behavior:__

App should recognize environment variables so users can configure token, org, etc.

__Current Behavior:__

`INFLUX_TOKEN=***` should be `INFLUX_TOKEN=hellotoken` in this example:

```
$  export INFLUX_TOKEN="hellotoken"
$  yarn start
yarn run v1.22.10
$ cd server && yarn start
$ node index.js
Enable proxy from /influx/* to http://localhost:9999/*
Unable to determine whether InfluxDB at http://localhost:9999 is onboarded. Error: connect ECONNREFUSED 127.0.0.1:9999
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1133:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9999
}
INFLUX_URL=http://localhost:9999
INFLUX_TOKEN=***
INFLUX_ORG=my-org
INFLUX_BUCKET=iot_center
Listening on http://localhost:5000
```

The code here does not appear to be working: https://github.com/bonitoo-io/iot-center-v2/blob/master/app/server/env.js.

**Comment by sranka** [comment]
sensitive data (such password and token) are not printed to console, that's why ... I don't think that this is a defect; INFLUX_ORG, INFLUX_TOKEN and INFLUX_URL can be overridden with environment variables, INFLUX_BUCKET is a constant

**Comment by pierwill** [comment]
Ah! That makes sense. I will try again!
