### ISSUE TITLE
Cannot set influx_url for python client

### ISSUE THREAD

**Issue by pierwill** [bonitoo-io/iot-center-v2#28]
### Current behavior

My environment is three machines:

- a "server" laptop running IoT Center and InfluxDB
- a raspberry pi using the [python client](https://github.com/bonitoo-io/iot-center-v2/blob/master/client_python/client_python.py)
- a "dev" laptop to interact with the server and pi over ssh

The IoT center is able to access influxdb and I am able to connect to IoT Center and influxdb in the browser from the dev laptop.

The pi is able to successfully register. However, the pi cannot write data to influxdb. When I run the client I get this:

```
Received configuration: {
    "influx_url": "http://localhost:8086",
[...]
The retriable error occurred during request. Reason: '<urllib3.connection.HTTPConnection object at xxxxx>: Failed to establish a new connection: [Errno 111] Connection refused'.
```

`localhost` should be the hostname of my server laptop; let's say `http://server:8086`. The client does not get the `INFLUX_URL` environment variable. It looks like the `localhost` address is coming from [`config_received` here](https://github.com/bonitoo-io/iot-center-v2/blob/master/client_python/client_python.py#L97).

### Expected behavior
I'd like to configure the URL of InfluxDB for the python client via an environment variable.

**Comment by sranka** [comment]
INFLUX_URL is configured during start of IoT Center application with environment variable `INFLUX_URL`. Use a URL with full hostname of InfluxDB, do not use localhost.
